export enum QUERY_KEY {
  MY_ACCOUNT = 'MY_ACCOUNT',
  USER = 'USER',
  USERS = 'USERS',
  ROOMS = 'ROOMS',
  ROOMS_FLOOR_PLAN = 'ROOMS_FLOOR_PLAN',
  AVAILABLE_ROOMS = 'AVAILABLE_ROOMS',
  ROOM = 'ROOM',
  BOOKINGS = 'BOOKINGS',
  BOOKING = 'BOOKING',
}
